# Array of instances to back up
instances:
  - name: ''
    bucket: ''
    database: ''

# Database configuration
database:
  username: ''
  password: ''
  host: ''
  port: ''
  pgDumpPath: ''

# s3cms configuration
s3cmd:
  s3cmdPath: ''

# The directory in which all backups will be stored.
# In the given directory a subdirectory called "localcrag_backups" will be created that contains
# one directory per instance
backupDirectory: ''

# SMTP config for failure emails
smtp:
  host: ''
  port: ''
  user: ''
  password: ''
  sender: ''
  receiver: ''