name: Linting Pipeline
on:
  pull_request:
    branches:
      - main
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  lint-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install pipenv
          cd server/src
          pipenv install --dev

      - name: Run Flake8
        run: pipenv run flake8 .

      - name: Run Black
        run: pipenv run black --check .

      - name: Run Isort
        run: pipenv run isort --check-only .